spring.application.name=User-Management-System

# 1. 資料庫連線設定 (請將 user_management_db 改成你實際建立的資料庫名稱)
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_db?serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Fs123456

# 2. JPA / Hibernate 設定
# update 代表 Spring Boot 啟動時，會自動根據你的 Java Entity 在資料庫中「自動建表」或更新欄位
spring.jpa.hibernate.ddl-auto=update
# 在 VS Code 主控台（Console）顯示實際執行的 SQL 語句，方便你檢查 CRUD 是否正確
spring.jpa.show-sql=true
# 讓顯示的 SQL 語句排版，比較好閱讀
spring.jpa.properties.hibernate.format_sql=true